#!/usr/bin/env python3.8

# import re
# string = "int value = -10.0;"

# reg = re.compile("[-+]?\d*\.?\d+")

# results = reg.findall(string)
# print(results)

class Person():
    def __init__(self, name, response):
        self.name = name
        self.response = response

def contains(container, function):
    return [element for element in container if(function(element))]

elements = []
for x in range(0, 10):
    elements.append(Person("Bob", x))

winner = contains(elements, lambda x: x.response == 2)
print(winner)
